kind: Pod
apiVersion: v1
metadata:
  name: rock-app
  labels:
    app: rock
spec:
  containers:
    - name: rock-app
      image: hashicorp/http-echo
      args:
        - "-text=rock"
      ports:
        - name: rock
          containerPort: 5678
          protocol: TCP
      resources:
        - limits: 
          cpu: 50m
          memory: 120m
        - requests:
          cpu: 10
          memory: 240m
---
kind: Service
apiVersion: v1
metadata:
  name: rock-service
spec:
  selector:
    app: rock
  ports:
    - port: 5678 # Default port for image
---
kind: Pod
apiVersion: v1
metadata:
  name: roll-app
  labels:
    app: roll
spec:
  containers:
    - name: roll-app
      image: hashicorp/http-echo
      args:
        - "-text=roll"
      resources:
        - limits: 
          cpu: 50m
          memory: 120m
        - requests:
          cpu: 10
          memory: 240m
---
kind: Service
apiVersion: v1
metadata:
  name: roll-service
spec:
  selector:
    app: roll
  ports:
    - port: 5678 # Default port for image
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/rock"
        backend:
          service:
            name: rock-service
            port:
              number: 5678
      - pathType: Prefix
        path: "/roll"
        backend:
          service:
            name: roll-service
            port:
              number: 5678