apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store-vault
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "my-passwords" #Path in vault
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-my-app-token" #Secret name created in kubernetes for vault token
          key: "token" #Key used for storing token
