apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-my-app-pass
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: cluster-secret-store-vault
    kind: ClusterSecretStore
  target:
    name: vault-my-passwords-my-app-pass # secret name that will be created after sync
    creationPolicy: Owner
  data:
  - secretKey: user # key of the secret that will be created after sync
    remoteRef:
      key: my-passwords/my-app-pass #path of your data in vault
      property: user #key that will be searched in vault
  - secretKey: pass
    remoteRef:
      key: my-passwords/my-app-pass
      property: pass